# FROM pypy:3.10-slim

# WORKDIR /app

# RUN apt-get update && apt-get install -y git

# COPY requirements.txt /app/
# RUN pip install --no-cache-dir -r requirements.txt

# COPY . /app

# EXPOSE 5500

# ENV FLASK_APP=run.py
# ENV FLASK_RUN_PORT=5500

# CMD ["pypy", "run.py"]


# heroku
FROM pypy:3.10-slim

WORKDIR /app

# Ensure packages are available and install build essentials explicitly
RUN apt-get update && \
    apt-get install -y git gcc libc-dev pypy3-dev make && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 5500

ENV FLASK_APP=run.py

RUN adduser --disabled-password --gecos '' myuser
USER myuser

CMD ["sh", "-c", "pypy run.py run --host=0.0.0.0 --port=$PORT"]

