version: '3.8'
services:
  web:
    build: .
    ports:
      - "5500:5500"
    volumes:
      - .:/code
    command: python app.py
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - worker

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis